### ISSUE TITLE
pkg error Error! No available node version satisfies 'node9'

### ISSUE THREAD

**Issue by nionis** [XLNT/gnarly#22]
this is the issue https://github.com/zeit/pkg/issues/331

updating gnarly-bin/package.json from ^4.3.1 to 4.3.1 fixes the issue

**Comment by shrugs** [comment]
I recently cloned the project, built the project, and then ran `yarn run deploy`, which builds the pkg and docker file. This succeeded twice now, so I'm going to consider this fixed for now!
